name: Build images
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build builder image
        working-directory: ./Builder
        run: docker build -t docker.pkg.github.com/ledermann/docker-rails-base/rails-base-builder:latest .

      - name: Build final image
        working-directory: ./Final
        run: docker build -t docker.pkg.github.com/ledermann/docker-rails-base/rails-base-final:latest .

      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push the images
        run: |
          docker push docker.pkg.github.com/ledermann/docker-rails-base/rails-base-builder:latest
          docker push docker.pkg.github.com/ledermann/docker-rails-base/rails-base-final:latest
